language: r
r:
  - release
cache: packages

bioc_packages: 
  - BiocGenerics
  - Biostrings
  - GenomicRanges
  - IRanges
  - S4Vectors
  - SummarizedExperiment
  - Rsamtools
  - VariantAnnotation
  - snpStats

r_github_packages:
  - explodecomputer/genetics.binaRies

warnings_are_errors: false

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
